const womenData = [
  {
    id: 1,
    name: "Generations Tank Top",
    img: "/img/women/women_1/1.jpg",
    price: 125,
    type: "Women Original",
    url: "/Generations_Tank_Top",
  },
  {
    id: 2,
    name: "COED Overshirt",
    img: "/img/women/women_2/1.jpg",
    price: 128,
    type: "Women Original",
    url: "/COED_Overshirt",
  },
  {
    id: 3,
    name: "Tweed Jacket Top",
    img: "/img/women/women_3/1.jpg",
    price: 115,
    type: "Women Original",
    url: "/Tweed_Jacket_Top",
  },
  {
    id: 4,
    name: "Cut And Sew Hoodie",
    img: "/img/women/women_4/1.jpg",
    price: 137,
    type: "Women Original",
    url: "/Cut_And_Sew_Hoodie",
  },
  {
    id: 5,
    name: "Stripe Square Neck T-Shirt",
    img: "/img/women/women_5/1.jpg",
    price: 180,
    type: "Women Original",
    url: "/Stripe_Square_Neck_T-Shirt",
  },
  {
    id: 6,
    name: "Generations Ribbed Black Tank Top",
    img: "/img/women/women_6/1.jpg",
    price: 90,
    type: "Women Original",
    url: "/Generations_Ribbed_Black_Tank_Top",
  },
  {
    id: 7,
    name: "Generations Ribbed Tank Top",
    img: "/img/women/women_7/1.jpg",
    price: 199,
    type: "Women Original",
    url: "/Generations_Ribbed_Tank_Top",
  },
  {
    id: 8,
    name: "Tie Dye Garthered Side Top",
    img: "/img/women/women_8/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Tie_Dye_Garthered_Side_Top",
  },
  {
    id: 9,
    name: "ALPHA Micro Tote Bag With Printed Straps",
    img: "/img/women/women_9/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/ALPHA_Micro_Tote_Bag_With_Printed_Straps",
  },
  {
    id: 10,
    name: "Jacquard Midi Dress With Collar",
    img: "/img/women/women_10/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Jacquard_Midi_Dress_With_Collar",
  },
  {
    id: 11,
    name: "Generations Waffle Dress",
    img: "/img/women/women_11/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Generations_Waffle_Dress",
  },
  {
    id: 12,
    name: "Generations Ribbed A-Line Sleeveless Dress",
    img: "/img/women/women_12/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Generations_Ribbed_A-Line_Sleeveless_Dress",
  },
  {
    id: 13,
    name: "Basic Pullover",
    img: "/img/women/women_13/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Basic_Pullover",
  },
];

const menData = [
  {
    id: 1,
    name: "COED Unisex Oversized Pocket T-Shirt",
    img: "/img/men/men_1/1.jpg",
    price: 112,
    type: "men",
    url: "/COED_Unisex_Oversized_Pocket_T-Shirt",
  },
  {
    id: 2,
    name: "Alternative Culture Graphic Hoodie With Backprint",
    img: "/img/men/men_2/1.jpg",
    price: 155,
    type: "Men Original",
    url: "/Alternative_Culture_Graphic_Hoodie_With_Backprint",
  },
  {
    id: 3,
    name: "Men's Premium Threads Velcro Sliders With Stripes Detail",
    img: "/img/men/men_3/1.jpg",
    price: 89,
    type: "Men Original",
    url: "/Men's_Premium_Threads_Velcro_Sliders_With_Stripes_Detail",
  },
  {
    id: 4,
    name: "Men's Logo Pullover With Special Print",
    img: "/img/men/men_4/1.jpg",
    price: 159,
    type: "Men Original",
    url: "/Men's_Logo_Pullover_With_Special_Print",
  },
  {
    id: 5,
    name: "Men's Regular Hoodie With Special Print",
    img: "/img/men/men_5/1.jpg",
    price: 109,
    type: "Men Original",
    url: "/Men's_Regular_Hoodie_With Special_Print",
  },
  {
    id: 6,
    name: "Unisex Trousers Pants With Drawstring",
    img: "/img/men/men_6/1.jpg",
    price: 105,
    type: "Men Original",
    url: "/Unisex_Trousers_Pants_With_Drawstring",
  },
  {
    id: 7,
    name: "ALPHA Regular Backpack",
    img: "/img/men/men_7/1.jpg",
    price: 128,
    type: "Men Original",
    url: "/ALPHA_Regular_Backpack",
  },
  {
    id: 8,
    name: "ALPHA Regular Black Backpack",
    img: "/img/men/men_8/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/ALPHA_Regular_Black_Backpack",
  },
  {
    id: 9,
    name: "Premium Threads Raglan T-Shirt With Shoulder Stripes",
    img: "/img/men/men_9/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Premium_Threads_Raglan_T-Shirt_With_Shoulder_Stripes",
  },
  {
    id: 10,
    name: "COED Single Band Sliders With Embossed Embro",
    img: "/img/men/men_10/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/COED_Single_Band_Sliders_With_Embossed_Embro",
  },
  {
    id: 11,
    name: "X Bi-Fold Wallet",
    img: "/img/men/men_11/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/X_Bi-Fold_Wallet",
  },
  {
    id: 12,
    name: "ALPHA Sling Bag",
    img: "/img/men/men_12/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/ALPHA_Sling_Bag",
  },
  {
    id: 13,
    name: "Pullover Sweater With Logo",
    img: "/img/men/men_13/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Pullover_Sweater_With_Logo",
  },
  {
    id: 14,
    name: "Skinny Jeans",
    img: "/img/men/men_14/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Skinny_Jeans",
  },
  {
    id: 15,
    name: "COED Unisex T-Shirt",
    img: "/img/men/men_15/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/COED_Unisex_T-Shirt",
  },
  {
    id: 16,
    name: "Tie Dye Pullover Sweater With Logo",
    img: "/img/men/men_16/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Tie_Dye_Pullover_Sweater_With_Log",
  },
];

const kidData = [
  {
    id: 1,
    name: "Kyoto & Tokyo High Kids Unisex Graphic T-Shirt",
    img: "/img/kid/kid_1/1.jpg",
    price: 195,
    type: "Kid Original",
    url: "/Kyoto_&_Tokyo_High_Kids_Unisex_Graphic_T-Shirt",
  },
  {
    id: 2,
    name: "Generations Unisex Kids Zip Up Hoodie With Logo",
    img: "/img/kid/kid_2/1.jpg",
    price: 145,
    type: "Kid Original",
    url: "/Generations_Unisex_Kids_Zip_Up_Hoodie_With_Logo",
  },
  {
    id: 3,
    name: "BLEACH x Kon Kids Unisex Graphic T-Shirt",
    img: "/img/kid/kid_3/1.jpg",
    price: 97,
    type: "Kid Original",
    url: "/BLEACH_x_Kon_Kids_Unisex_Graphic_T-Shirt",
  },
  {
    id: 4,
    name: "Generations Kids Shorts",
    img: "/img/kid/kid_4/1.jpg",
    price: 129,
    type: "Kid Original",
    url: "/Generations_Kids_Shorts",
  },
  {
    id: 5,
    name: "Generations Kids Unisex Shorts",
    img: "/img/kid/kid_5/1.jpg",
    price: 85,
    type: "Kid Original",
    url: "/Generations_Kids_Unisex_Shorts",
  },
  {
    id: 6,
    name: "Jujutsu Kaisen x Kids Curved Cap",
    img: "/img/kid/kid_6/1.jpg",
    price: 115,
    type: "Kid Original",
    url: "/Jujutsu_Kaisen_x_Kids_Curved_Cap",
  },
  {
    id: 7,
    name: "Generations Kids Beanie With Embroidered Patch",
    img: "/img/kid/kid_7/1.jpg",
    price: 182,
    type: "Kid Original",
    url: "/Generations_Kids_Beanie_With_Embroidered_Patch",
  },
  {
    id: 8,
    name: "YuYu Hakusho x ALPHA Kids Curved Cap",
    img: "/img/kid/kid_8/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/YuYu_Hakusho_x_ALPHA_Kids_Curved_Cap",
  },
  {
    id: 9,
    name: "YuYu Hakusho Kids Pullover With Graphic Print",
    img: "/img/kid/kid_9/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/YuYu_Hakusho_Kids_Pullover_With_Graphic_Print",
  },
  {
    id: 10,
    name: "YuYu Hakusho Kids T-Shirt With Graphic Print",
    img: "/img/kid/kid_10/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/YuYu_Hakusho_Kids_T-Shirt_With_Graphic_Print",
  },
  {
    id: 11,
    name: "Generations Female Kids Zip Up Hoodie With Logo",
    img: "/img/kid/kid_11/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/Generations_Female_Kids_Zip_Up_Hoodie_With_Logo",
  },
  {
    id: 12,
    name: "Generations Unisex Kids T-Shirt With Logo",
    img: "/img/kid/kid_12/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/Generations_Unisex_Kids_T-Shirt_With_Logo",
  },
  {
    id: 13,
    name: "Generations Male Kids T-Shirt With Logo",
    img: "/img/kid/kid_13/1.jpg",
    price: 120,
    type: "Kid Original",
    url: "/Generations_Male_Kids_T-Shirt_With_Logo",
  },
];

const careData = [
  {
    id: 1,
    name: "BLEACH x Ichigo 11:55 Ichigo Limited Edition Eau de Toilette for Men",
    price: 499,
    type: "Impact 4",
    img: "/img/care/care_1/1.jpg",
    url: "/BLEACH_x_Ichigo_11:55_Ichigo_Limited_Edition_Eau_de_Toilette_for_Men",
  },
  {
    id: 2,
    name: "Wild Love Eau de Toilette for Women",
    price: 379,
    type: "Training Shoes",
    img: "/img/care/care_2/1.jpg",
    url: "/Wild_Love_Eau_de_Toilette_for_Women",
  },
  {
    id: 3,
    name: "Pitch Black Eau de Toilette for Men",
    price: 399,
    type: "Football Boot",
    img: "/img/care/care_3/1.jpg",
    url: "/Pitch_Black_Eau_de_Toilette_for_Men",
  },
  {
    id: 4,
    name: "OXGN Eau de Toilette for Men",
    price: 399,
    type: "Waterproof",
    img: "/img/care/care_4/1.jpg",
    url: "/ALPHA_Eau_de_Toilette_for_Men",
  },
  {
    id: 5,
    name: "Noir_Eau_de_Toilette_for_Men",
    price: 399,
    type: "Basketball Shoes",
    img: "/img/care/care_5/1.jpg",
    url: "/Noir_Eau_de_Toilette_for_Men",
  },
  {
    id: 6,
    name: "Static Eau de Toilette for Men",
    price: 260,
    type: "Younger Kids' Shoes",
    img: "/img/care/care_6/1.jpg",
    url: "/Static_Eau_de_Toilette_for_Men",
  },
  {
    id: 7,
    name: "Unapologetic Eau de Toilette for Women",
    price: 265,
    type: "Court Tennis Shoes",
    img: "/img/care/care_7/1.jpg",
    url: "/Unapologetic_Eau_de_Toilette_for_Women",
  },
  {
    id: 8,
    name: "Alpha x DemonSlayer Static Eau de Toilette for Men",
    price: 399,
    type: "Court Tennis Shoes",
    img: "/img/care/care_8/1.jpg",
    url: "/Alpha_x_DemonSlayer_Static_Eau_de_Toilette_for_Men",
  },
  {
    id: 9,
    name: "G.A.S. Eau de Toilette for Men",
    price: 399,
    type: "Court Tennis Shoes",
    img: "/img/care/care_9/1.jpg",
    url: "/G.A.S._Eau_de_Toilette_for_Men",
  },
];

const newArrival = [
  {
    id: 1,
    name: "Generations Dad Hat",
    price: 105,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_1/1.jpg",
    url: "/generations_dad_hat",
    stock: "In Stock",
  },
  {
    id: 2,
    name: "Evangelion x Unisex EVA 01 Shoes",
    price: 235,
    type: "Unisex",
    img: "/img/arrival/arrival_2/1.jpg",
    url: "/Evangelion_x_Unisex_EVA_01_Shoes",
    stock: "In Stock",
  },
  {
    id: 3,
    name: "COED Curved Cap With Metal Logo",
    price: 140,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_3/1.jpg",
    url: "/COED_Curved_Cap_With_Metal_Logo",
    stock: "In Stock",
  },
  {
    id: 4,
    name: "Generations Kids Bucket Hat",
    price: 170,
    type: "Women's Shoes",
    img: "/img/arrival/arrival_4/1.jpg",
    url: "/Generations_Kids_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 5,
    name: "Men's COED Double Strap Sandals",
    price: 199,
    type: "Unisex",
    img: "/img/arrival/arrival_5/1.jpg",
    url: "/Men's_COED_Double_Strap_Sandals",
    stock: "In Stock",
  },
  {
    id: 6,
    name: "Mobile Suit Gundam x ALPHA Bucket Hat",
    price: 138,
    type: "Custom Men's Shoes",
    img: "/img/arrival/arrival_6/1.jpg",
    url: "/Mobile_Suit_Gundam_x_OXGN_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 7,
    name: "Jujutsu Kaisen x Reversible Bucket Hat",
    price: 115,
    type: "Custom Men's Shoe",
    img: "/img/arrival/arrival_7/1.jpg",
    url: "/Jujutsu_Kaisen_x_Reversible_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 8,
    name: "Evangelion x ALPHA Trio Kids Graphic T-Shirt",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_8/1.jpg",
    url: "/Evangelion_x_OXGN_Trio_Kids_Graphic_T-Shirt",
    stock: "In Stock",
  },
  {
    id: 9,
    name: "Evangelion x ALPHA Joggers",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_9/1.jpg",
    url: "/Evangelion_x_Joggers",
    stock: "In Stock",
  },
  {
    id: 10,
    name: "Evangelion x Curved Cap",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_10/1.jpg",
    url: "/Evangelion_x_Curved_Cap",
    stock: "In Stock",
  },
  {
    id: 11,
    name: "Evangelion x Bum Bag",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_11/1.jpg",
    url: "/Evangelion_x_Bum_Bag",
    stock: "In Stock",
  },
];

// SECTION 3
const section_3 = [
  {
    id: 1,
    name: "Evangelion x ALPHA ced Sling Bag",
    price: 499,
    img: "/img/hot/hot_1/1.jpg",
    url: "Evangelion_x_ALPHA_ced_Sling_Bag",
  },
  {
    id: 2,
    name: "Mobile Suit Gundam x ALPHA Convertible Backpack",
    price: 699,
    img: "/img/hot/hot_2/1.jpg",
    url: "Mobile_Suit_Gundam_x_ALPHA_Convertible_Backpack",
  },
  {
    id: 3,
    name: "Evangelion x ALPHA Sling Bag",
    price: 499,
    img: "/img/hot/hot_3/1.jpg",
    url: "Evangelion_x_ALPHA_Sling_Bag",
  },
  {
    id: 4,
    name: "Logo Regular Fit Graphic T-Shirt",
    price: 499,
    img: "/img/hot/hot_4/1.jpg",
    url: "Logo_Regular_Fit_Graphic_T-Shirt",
  },
  {
    id: 5,
    name: "Escapism Oversized Graphic T-Shirt",
    price: 699,
    img: "/img/hot/hot_5/1.jpg",
    url: "Escapism_Oversized_Graphic_T-Shirt",
  },
  {
    id: 6,
    name: "Jujutsu Kaisen x ALPHA Sukuna T-Shirt Gradient",
    price: 499,
    img: "/img/hot/hot_6/1.jpg",
    url: "Jujutsu_Kaisen_x_ALPHA_Sukuna_T-Shirt_Gradient",
  },
  {
    id: 7,
    name: "BLEACH x Alpha Renji Unisex Fit Overdyed Graphic T-Shirt",
    price: 699,
    img: "/img/hot/hot_7/1.jpg",
    url: "BLEACH_x_Alpha_Renji_Unisex_Fit_Overdyed_Graphic_T-Shirt",
  },
  {
    id: 8,
    name: "Jujutsu Kaisen x ALPHA 4 Heroes Tie Dye T-Shirt",
    price: 699,
    img: "/img/hot/hot_8/1.jpg",
    url: "Jujutsu_Kaisen_x_ALPHA_4_Heroes_Tie_Dye_T-Shirt",
  },
];

const allData = [
  {
    id: 1,
    name: "COED Unisex Oversized Pocket T-Shirt",
    img: "/img/men/men_1/1.jpg",
    price: 112,
    type: "men",
    url: "/COED_Unisex_Oversized_Pocket_T-Shirt",
  },
  {
    id: 2,
    name: "Alternative Culture Graphic Hoodie With Backprint",
    img: "/img/men/men_2/1.jpg",
    price: 155,
    type: "Men Original",
    url: "/Alternative_Culture_Graphic_Hoodie_With_Backprint",
  },
  {
    id: 3,
    name: "Men's Premium Threads Velcro Sliders With Stripes Detail",
    img: "/img/men/men_3/1.jpg",
    price: 89,
    type: "Men Original",
    url: "/Men's_Premium_Threads_Velcro_Sliders_With_Stripes_Detail",
  },
  {
    id: 4,
    name: "Men's Logo Pullover With Special Print",
    img: "/img/men/men_4/1.jpg",
    price: 159,
    type: "Men Original",
    url: "/Men's_Logo_Pullover_With_Special_Print",
  },
  {
    id: 5,
    name: "Men's Regular Hoodie With Special Print",
    img: "/img/men/men_5/1.jpg",
    price: 109,
    type: "Men Original",
    url: "/Men's_Regular_Hoodie_With Special_Print",
  },
  {
    id: 6,
    name: "Unisex Trousers Pants With Drawstring",
    img: "/img/men/men_6/1.jpg",
    price: 105,
    type: "Men Original",
    url: "/Unisex_Trousers_Pants_With_Drawstring",
  },
  {
    id: 7,
    name: "ALPHA Regular Backpack",
    img: "/img/men/men_7/1.jpg",
    price: 128,
    type: "Men Original",
    url: "/ALPHA_Regular_Backpack",
  },
  {
    id: 8,
    name: "ALPHA Regular Black Backpack",
    img: "/img/men/men_8/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/ALPHA_Regular_Black_Backpack",
  },
  {
    id: 9,
    name: "Premium Threads Raglan T-Shirt With Shoulder Stripes",
    img: "/img/men/men_9/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Premium_Threads_Raglan_T-Shirt_With_Shoulder_Stripes",
  },
  {
    id: 10,
    name: "COED Single Band Sliders With Embossed Embro",
    img: "/img/men/men_10/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/COED_Single_Band_Sliders_With_Embossed_Embro",
  },
  {
    id: 11,
    name: "X Bi-Fold Wallet",
    img: "/img/men/men_11/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/X_Bi-Fold_Wallet",
  },
  {
    id: 12,
    name: "ALPHA Sling Bag",
    img: "/img/men/men_12/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/ALPHA_Sling_Bag",
  },
  {
    id: 13,
    name: "Pullover Sweater With Logo",
    img: "/img/men/men_13/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Pullover_Sweater_With_Logo",
  },
  {
    id: 14,
    name: "Skinny Jeans",
    img: "/img/men/men_14/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Skinny_Jeans",
  },
  {
    id: 15,
    name: "COED Unisex T-Shirt",
    img: "/img/men/men_15/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/COED_Unisex_T-Shirt",
  },
  {
    id: 16,
    name: "Tie Dye Pullover Sweater With Logo",
    img: "/img/men/men_16/1.jpg",
    price: 102,
    type: "Men Original",
    url: "/Tie_Dye_Pullover_Sweater_With_Log",
  },
  {
    id: 17,
    name: "Evangelion x ALPHA ced Sling Bag",
    price: 499,
    img: "/img/hot/hot_1/1.jpg",
    url: "Evangelion_x_ALPHA_ced_Sling_Bag",
  },
  {
    id: 18,
    name: "Mobile Suit Gundam x ALPHA Convertible Backpack",
    price: 699,
    img: "/img/hot/hot_2/1.jpg",
    url: "Mobile_Suit_Gundam_x_ALPHA_Convertible_Backpack",
  },
  {
    id: 19,
    name: "Evangelion x ALPHA Sling Bag",
    price: 499,
    img: "/img/hot/hot_3/1.jpg",
    url: "Evangelion_x_ALPHA_Sling_Bag",
  },
  {
    id: 20,
    name: "Logo Regular Fit Graphic T-Shirt",
    price: 499,
    img: "/img/hot/hot_4/1.jpg",
    url: "Logo_Regular_Fit_Graphic_T-Shirt",
  },
  {
    id: 21,
    name: "Escapism Oversized Graphic T-Shirt",
    price: 699,
    img: "/img/hot/hot_5/1.jpg",
    url: "Escapism_Oversized_Graphic_T-Shirt",
  },
  {
    id: 22,
    name: "Jujutsu Kaisen x ALPHA Sukuna T-Shirt Gradient",
    price: 499,
    img: "/img/hot/hot_6/1.jpg",
    url: "Jujutsu_Kaisen_x_ALPHA_Sukuna_T-Shirt_Gradient",
  },
  {
    id: 23,
    name: "BLEACH x Alpha Renji Unisex Fit Overdyed Graphic T-Shirt",
    price: 699,
    img: "/img/hot/hot_7/1.jpg",
    url: "BLEACH_x_Alpha_Renji_Unisex_Fit_Overdyed_Graphic_T-Shirt",
  },
  {
    id: 24,
    name: "Jujutsu Kaisen x ALPHA 4 Heroes Tie Dye T-Shirt",
    price: 699,
    img: "/img/hot/hot_8/1.jpg",
    url: "Jujutsu_Kaisen_x_ALPHA_4_Heroes_Tie_Dye_T-Shirt",
  },
  {
    id: 25,
    name: "Generations Tank Top",
    img: "/img/women/women_1/1.jpg",
    price: 125,
    type: "Women Original",
    url: "/Generations_Tank_Top",
  },
  {
    id: 26,
    name: "COED Overshirt",
    img: "/img/women/women_2/1.jpg",
    price: 128,
    type: "Women Original",
    url: "/COED_Overshirt",
  },
  {
    id: 27,
    name: "Tweed Jacket Top",
    img: "/img/women/women_3/1.jpg",
    price: 115,
    type: "Women Original",
    url: "/Tweed_Jacket_Top",
  },
  {
    id: 28,
    name: "Cut And Sew Hoodie",
    img: "/img/women/women_4/1.jpg",
    price: 137,
    type: "Women Original",
    url: "/Cut_And_Sew_Hoodie",
  },
  {
    id: 29,
    name: "Stripe Square Neck T-Shirt",
    img: "/img/women/women_5/1.jpg",
    price: 180,
    type: "Women Original",
    url: "/Stripe_Square_Neck_T-Shirt",
  },
  {
    id: 30,
    name: "Generations Ribbed Black Tank Top",
    img: "/img/women/women_6/1.jpg",
    price: 90,
    type: "Women Original",
    url: "/Generations_Ribbed_Black_Tank_Top",
  },
  {
    id: 31,
    name: "Generations Ribbed Tank Top",
    img: "/img/women/women_7/1.jpg",
    price: 199,
    type: "Women Original",
    url: "/Generations_Ribbed_Tank_Top",
  },
  {
    id: 32,
    name: "Tie Dye Garthered Side Top",
    img: "/img/women/women_8/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Tie_Dye_Garthered_Side_Top",
  },
  {
    id: 33,
    name: "ALPHA Micro Tote Bag With Printed Straps",
    img: "/img/women/women_9/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/ALPHA_Micro_Tote_Bag_With_Printed_Straps",
  },
  {
    id: 34,
    name: "Jacquard Midi Dress With Collar",
    img: "/img/women/women_10/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Jacquard_Midi_Dress_With_Collar",
  },
  {
    id: 35,
    name: "Generations Waffle Dress",
    img: "/img/women/women_11/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Generations_Waffle_Dress",
  },
  {
    id: 36,
    name: "Generations Ribbed A-Line Sleeveless Dress",
    img: "/img/women/women_12/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Generations_Ribbed_A-Line_Sleeveless_Dress",
  },
  {
    id: 37,
    name: "Basic Pullover",
    img: "/img/women/women_13/1.jpg",
    price: 168,
    type: "Women Original",
    url: "/Basic_Pullover",
  },
  {
    id: 38,
    name: "BLEACH x Ichigo 11:55 Ichigo Limited Edition Eau de Toilette for Men",
    price: 499,
    type: "Impact 4",
    img: "/img/care/care_1/1.jpg",
    url: "/BLEACH_x_Ichigo_11:55_Ichigo_Limited_Edition_Eau_de_Toilette_for_Men",
  },
  {
    id: 39,
    name: "Wild Love Eau de Toilette for Women",
    price: 379,
    type: "Training Shoes",
    img: "/img/care/care_2/1.jpg",
    url: "/Wild_Love_Eau_de_Toilette_for_Women",
  },
  {
    id: 40,
    name: "Pitch Black Eau de Toilette for Men",
    price: 399,
    type: "Football Boot",
    img: "/img/care/care_3/1.jpg",
    url: "/Pitch_Black_Eau_de_Toilette_for_Men",
  },
  {
    id: 41,
    name: "OXGN Eau de Toilette for Men",
    price: 399,
    type: "Waterproof",
    img: "/img/care/care_4/1.jpg",
    url: "/ALPHA_Eau_de_Toilette_for_Men",
  },
  {
    id: 42,
    name: "Noir_Eau_de_Toilette_for_Men",
    price: 399,
    type: "Basketball Shoes",
    img: "/img/care/care_5/1.jpg",
    url: "/Noir_Eau_de_Toilette_for_Men",
  },
  {
    id: 43,
    name: "Static Eau de Toilette for Men",
    price: 260,
    type: "Younger Kids' Shoes",
    img: "/img/care/care_6/1.jpg",
    url: "/Static_Eau_de_Toilette_for_Men",
  },
  {
    id: 44,
    name: "Unapologetic Eau de Toilette for Women",
    price: 265,
    type: "Court Tennis Shoes",
    img: "/img/care/care_7/1.jpg",
    url: "/Unapologetic_Eau_de_Toilette_for_Women",
  },
  {
    id: 45,
    name: "Alpha x DemonSlayer Static Eau de Toilette for Men",
    price: 399,
    type: "Court Tennis Shoes",
    img: "/img/care/care_8/1.jpg",
    url: "/Alpha_x_DemonSlayer_Static_Eau_de_Toilette_for_Men",
  },
  {
    id: 46,
    name: "G.A.S. Eau de Toilette for Men",
    price: 399,
    type: "Court Tennis Shoes",
    img: "/img/care/care_9/1.jpg",
    url: "/G.A.S._Eau_de_Toilette_for_Men",
  },
  {
    id: 47,
    name: "Generations Dad Hat",
    price: 105,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_1/1.jpg",
    url: "/generations_dad_hat",
    stock: "In Stock",
  },
  {
    id: 48,
    name: "Evangelion x Unisex EVA 01 Shoes",
    price: 235,
    type: "Unisex",
    img: "/img/arrival/arrival_2/1.jpg",
    url: "/Evangelion_x_Unisex_EVA_01_Shoes",
    stock: "In Stock",
  },
  {
    id: 49,
    name: "COED Curved Cap With Metal Logo",
    price: 140,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_3/1.jpg",
    url: "/COED_Curved_Cap_With_Metal_Logo",
    stock: "In Stock",
  },
  {
    id: 50,
    name: "Generations Kids Bucket Hat",
    price: 170,
    type: "Women's Shoes",
    img: "/img/arrival/arrival_4/1.jpg",
    url: "/Generations_Kids_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 51,
    name: "Men's COED Double Strap Sandals",
    price: 199,
    type: "Unisex",
    img: "/img/arrival/arrival_5/1.jpg",
    url: "/Men's_COED_Double_Strap_Sandals",
    stock: "In Stock",
  },
  {
    id: 52,
    name: "Mobile Suit Gundam x ALPHA Bucket Hat",
    price: 138,
    type: "Custom Men's Shoes",
    img: "/img/arrival/arrival_6/1.jpg",
    url: "/Mobile_Suit_Gundam_x_OXGN_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 53,
    name: "Jujutsu Kaisen x Reversible Bucket Hat",
    price: 115,
    type: "Custom Men's Shoe",
    img: "/img/arrival/arrival_7/1.jpg",
    url: "/Jujutsu_Kaisen_x_Reversible_Bucket_Hat",
    stock: "In Stock",
  },
  {
    id: 54,
    name: "Evangelion x ALPHA Trio Kids Graphic T-Shirt",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_8/1.jpg",
    url: "/Evangelion_x_OXGN_Trio_Kids_Graphic_T-Shirt",
    stock: "In Stock",
  },
  {
    id: 55,
    name: "Evangelion x ALPHA Joggers",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_9/1.jpg",
    url: "/Evangelion_x_Joggers",
    stock: "In Stock",
  },
  {
    id: 56,
    name: "Evangelion x Curved Cap",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_10/1.jpg",
    url: "/Evangelion_x_Curved_Cap",
    stock: "In Stock",
  },
  {
    id: 57,
    name: "Evangelion x Bum Bag",
    price: 280,
    type: "Men's Shoes",
    img: "/img/arrival/arrival_11/1.jpg",
    url: "/Evangelion_x_Bum_Bag",
    stock: "In Stock",
  },
];

export default careData;
export { section_3, kidData, menData, womenData, newArrival, allData };
